name: Daily Tweet Scheduler

on:
  schedule:
    - cron: '15 1,4,6,18,22 * * *' # Scheduled at 10am, 2pm, 5pm, 8pm, and 10pm PST

jobs:
  post-tweet:
    runs-on: ubuntu-latest

    steps:
      - name: Post Tweet
        run: |
          curl -X POST https://nexttwitterv3x.vercel.app/api/twitter \
          -H "Content-Type: application/json" \
          -d '{"encryptedData": "${{ secrets.TWITTER_POSTER_KEY }}"}'
